name: Build and Deploy TruthLens Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and Start Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel

      - name: Install Dependencies with Retry
        run: |
          source venv/bin/activate
          for i in {1..5}; do pip install -r requirements.txt && break || sleep 15; done

      - name: Run Tests (Optional)
        run: |
          source venv/bin/activate
          if [ -f "pytest.ini" ] || [ -d "tests" ]; then 
            pytest
          else 
            echo "No tests found, skipping."
          fi

      - name: Build Application
        run: |
          source venv/bin/activate
          python -m compileall -q .

      - name: Zip Artifact for Deployment
        run: zip -r release.zip . -x "venv/*" "*.pyc" "__pycache__/*" ".git/*" "tests/*"

      - name: Upload Artifact for Deployment Jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Unzip Artifact for Deployment
        run: unzip -o release.zip -d .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'truth-lens-api-2'
          package: '.'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
